/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filepersistence_MainActivity */

#ifndef _Included_com_example_filepersistence_MainActivity
#define _Included_com_example_filepersistence_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filepersistence_MainActivity
 * Method:    saveData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_filepersistence_MainActivity_saveData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_filepersistence_MainActivity
 * Method:    loadData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_filepersistence_MainActivity_loadData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
